########################################
# パッケージ管理ツール
########################################
  [[plugins]]
    repo = 'Shougo/dein.vim'

########################################
# 表示に関するプラグイン
########################################

## カラースキーム(molokai)
  [[plugins]]
    repo = 'tomasr/molokai'
    hook_add = '''
      colorscheme molokai
    '''


########################################
# ファイラー
########################################

# あいまい検索 fzf
  [[plugins]]
    repo = 'junegunn/fzf'
    build = './install --bin'
    merged = '0'

  [[plugins]]
    repo = 'junegunn/fzf.vim'
    depends = ['junegunn/fzf']
    hook_add = '''
      " Prefix: <Leader>r
      nnoremap <Leader>rr :<C-u>GFiles<CR>
      nnoremap <Leader>rf :<C-u>Files<CR>
      nnoremap <Leader>rh :<C-u>History<CR>
      nnoremap <Leader>rg :<C-u>GFiles?<CR>
      nnoremap <Leader>rb :<C-u>Buffers<CR>
      nnoremap <Leader>rc :<C-u>History:<CR>
      nnoremap <Leader>rs :<C-u>History/<CR>
    '''


########################################
# ステータスラインに関するプラグイン
########################################

## ステータスライン
  [[plugins]]
    repo = 'itchyny/lightline.vim'
    hook_add = '''
      let g:lightline = { 'colorscheme': 'molokai' }
      set laststatus=2
      set noshowmode
    '''

########################################
# シンタックスに関するプラグイン
########################################

## Coffee Script
  [[plugins]]
    repo = 'kchmck/vim-coffee-script'
    on_ft = ['coffee']

## Slim
  [[plungins]]
    repo = 'slim-template/vim-slim'
    on_ft = ['slim']
