########################################
# パッケージ管理ツール
########################################
  [[plugins]]
    repo = 'Shougo/dein.vim'

########################################
# 表示に関するプラグイン
########################################

## カラースキーム(molokai)
  [[plugins]]
    repo = 'tomasr/molokai'
    hook_add = '''
      colorscheme molokai
    '''


########################################
# ファイラー
########################################

# あいまい検索 fzf
  [[plugins]]
    repo = 'junegunn/fzf'
    build = './install --bin'
    merged = '0'

  [[plugins]]
    repo = 'junegunn/fzf.vim'
    depends = ['junegunn/fzf']
    hook_add = '''
      " Prefix: <Leader>r
      nnoremap <Leader>rr :<C-u>GFiles<CR>
      nnoremap <Leader>f :<C-u>GFiles<CR>
      nnoremap <Leader>rf :<C-u>Files<CR>
      nnoremap <Leader>rh :<C-u>History<CR>
      nnoremap <Leader>g :<C-u>GFiles?<CR>
      nnoremap <Leader>rg :<C-u>GFiles?<CR>
      nnoremap <Leader>rb :<C-u>Buffers<CR>
      nnoremap <Leader>rc :<C-u>History:<CR>
      nnoremap <Leader>rs :<C-u>History/<CR>
    '''

########################################
# エディタに関するプラグイン
########################################

## インデントをわかりやすく
  [[plugins]]
    repo = 'Yggdroot/indentLine'
    hook_add = '''
      let g:indentLine_enabled = 1
      let g:indentLine_char = '|'
      set list
      set listchars=tab:▸\ ,trail:·
      highlight IndentLine guifg=#2A2A2A ctermfg=236
    '''


########################################
# ステータスラインに関するプラグイン
########################################

## ステータスライン
  [[plugins]]
    repo = 'itchyny/lightline.vim'
    hook_add = '''
      let g:lightline = { 'colorscheme': 'molokai' }
      set laststatus=2
      set noshowmode
    '''

########################################
# シンタックスに関するプラグイン
########################################

## Coffee Script
  [[plugins]]
    repo = 'kchmck/vim-coffee-script'
    on_ft = ['coffee']

## Slim
  [[plugins]]
    repo = 'slim-template/vim-slim'
    on_ft = ['slim']
