#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


alias rm="rm -f"
alias mv="mv -f"
alias cp="cp -f"

alias ls="ls --color=auto"
alias ll="ls -la"
alias vi=nvim

alias g=git
alias d=docker
alias dc=docker-compose
