#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt pure

export DESKTOP="$HOME/Desktop"
export DOWNLOAD="$HOME/Downloads"

# ==== Program environment settings

# fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# asdf
. ~/.asdf/asdf.sh

export PATH="~/bin:$PATH:$(yarn global bin)"
