#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath+=$HOME/.zfunctions
autoload -U promptinit; promptinit
prompt pure

export PATH="/Users/yu.takahashi/bin:$PATH"
export DESKTOP="$HOME/Desktop"
export DOWNLOAD="$HOME/Downloads"


export PATH="~/bin:$PATH:$(yarn global bin)"

# mise
eval "$(mise activate zsh)"

# fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

